### ISSUE TITLE
New MaptimeME site

### ISSUE THREAD

**Issue by geobrando** [maptime/maine#2]
Hey @jacquestardie : @NickKauf is looking to reboot MaptimeME.  Created an admin team so that he can manage this repo.  Cool with you?  Also, I see you had a custom domain that is no longer active.

Nick... Looks like this repo isn't using the starter template that many other chapters use.  (See http://maptime.io/starter). Currently, maptime.io/maine leads to a 404 page.  Let me know if you want to begin with the starter template, if you want to use whatever is here, or if you want to totally start from scratch.  As I think you're new to github I can help you out.

**Comment by geobrando** [comment]
Removed the cname file to see what the current site looks like.  Now served at http://maptime.io/maine

**Comment by jqtrde** [comment]
Yep, keep me posted on how I can help! I think MaptimeME may have been pre-started. Most of what infrastructure once existed is no longer there :sweat:

**Comment by NickKauf** [comment]
Hey, yeah I'll dig through this stuff when I get back home, starter template looks fine, I can use that for now, likewise for the meetup group
